=== Gustice/SmartDmxBridge/tools/ConfigurationSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "StationConfiguration",
    "description": "Schema to define a device configuration",
    "type": "object",
    "properties": {
        "dmxOutputs": {
            "description": "Number of DMX outputs",
            "type": "number",
            "minimum": 24,
            "maximum": 24,
            "default": 24
        },
        "illuminationWeights": {
            "description": "Weights for illumination channels. Theses are scaled with the intensity values and written to DMX-output. \nMissing elements will be filled with zeros",
            "type": "array",
            "maxItems": 24,
            "items": {
                "type": "integer",
                "minimum": 0,
                "maximum": 255
            }
        },
        "ambientChannels": {
            "description": "Channel indexes for ambient colors",
            "type": "object",
            "properties": {
                "foreground": {
                    "description": "Channel indexes for foreground color. These channels will be superposed with illumination data",
                    "type": "array",
                    "minItems": 3,
                    "maxItems": 3,
                    "items": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 24
                    }
                },
                "background": {
                    "description": "Channel indexes for background color. These channels will be superposed with illumination data",
                    "type": "array",
                    "minItems": 3,
                    "maxItems": 3,
                    "items": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 24
                    }
                }
            },
            "required": [
                "foreground",
                "background"
            ],
            "additionalProperties": false
        },
        "colorPresets": {
            "description": "Configured color presets, that can be selected by user",
            "type": "array",
            "minItems": 3,
            "maxItems": 3,
            "items": {
                "description": "Configured color presets",
                "type": "object",
                "properties": {
                    "foreground": {
                        "description": "RGB color value for foreground color",
                        "type": "array",
                        "minItems": 3,
                        "maxItems": 3,
                        "items": {
                            "type": "integer",
                            "minimum": 0,
                            "maximum": 255
                        }
                    },
                    "background": {
                        "description": "RGB color value for background color",
                        "type": "array",
                        "minItems": 3,
                        "maxItems": 3,
                        "items": {
                            "type": "integer",
                            "minimum": 0,
                            "maximum": 255
                        }
                    }
                },
                "required": [
                    "foreground",
                    "background"
                ],
                "additionalProperties": false
            
            }
        }
    },
    "required": [
        "dmxOutputs",
        "illuminationWeights",
        "ambientChannels",
        "colorPresets"
    ],
    "additionalProperties": false
}

=== Gustice/SmartDmxBridge/data/Configuration.json
{
    "dmxOutputs": 24, 
    "illuminationWeights": [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 127, 0, 0, 0, 255, 0, 255, 0, 255, 255, 255, 255  ],
    "ambientChannels": { 
        "foreground": [ 1, 2, 3 ],  
        "background": [ 6, 7, 8 ] 
    },
    "colorPresets": [ 
        {
            "foreground": [ 255, 0, 0 ], 
            "background": [ 0, 255, 0 ] 
        },
        {
            "foreground": [ 0, 255, 0 ], 
            "background": [ 0, 0,255 ] 
        },
        {
            "foreground": [ 0, 0, 255 ], 
            "background": [ 255, 0, 0 ] 
        }
    ]
}
